version: "3.9"
services:
  app:
    container_name: kairos
    image: kairos:latest
    restart: always

    ports:
      - 8090:8090

    volumes:
      - type: bind
        source: pb_data
        target: /app/pb_data

volumes:
  db-data: