export enum Theme {
	LIGHT = 'light',
	DARK = 'dark',
	CUPCAKE = 'cupcake',
	BUMBLEBEE = 'bumblebee',
	EMERALD = 'emerald',
	CORPORATE = 'corporate',
	SYNTHWAVE = 'synthwave',
	RETRO = 'retro',
	CYBERPUNK = 'cyberpunk',
	VALENTINE = 'valentine',
	HALLOWEEN = 'halloween',
	GARDEN = 'garden',
	FOREST = 'forest',
	AQUA = 'aqua',
	LOFI = 'lofi',
	PASTEL = 'pastel',
	FANTASY = 'fantasy',
	WIREFRAME = 'wireframe',
	BLACK = 'black',
	LUXURY = 'luxury',
	DRACULA = 'dracula',
	CMYK = 'cmyk',
	AUTUMN = 'autumn',
	BUSINESS = 'business',
	ACID = 'acid',
	LEMONADE = 'lemonade',
	NIGHT = 'night',
	COFFEE = 'coffee',
	WINTER = 'winter',
	DIM = 'dim',
	NORD = 'nord',
	SUNSET = 'sunset',
	CARAMELLATTE = 'caramellatte',
	ABYSS = 'abyss',
	SILK = 'silk',
	CHRISTMAS = 'christmas'
}

export enum LightThemes {
	LIGHT = "light",
	CUPCAKE = "cupcake",
	BUMBLEBEE = "bumblebee",
	EMERALD = "emerald",
	CORPORATE = "corporate",
	RETRO = "retro",
	CYBERPUNK = "cyberpunk",
	VALENTINE = "valentine",
	GARDEN = "garden",
	LOFI = "lofi",
	PASTEL = "pastel",
	FANTASY = "fantasy",
	WIREFRAME = "wireframe",
	CMYK = "cmyk",
	AUTUMN = "autumn",
	ACID = "acid",
	WINTER = "winter",
	NORD = "nord",
	CARAMELLATTE = "caramellatte",
	SILK = "silk",
	LEMONADE = "lemonade"
}

export enum DarkThemes {
	DARK = "dark",
	SYNTHWAVE = "synthwave",
	HALLOWEEN = "halloween",
	FOREST = "forest",
	AQUA = "aqua",
	BLACK = "black",
	LUXURY = "luxury",
	DRACULA = "dracula",
	BUSINESS = "business",
	NIGHT = "night",
	COFFEE = "coffee",
	DIM = "dim",
	SUNSET = "sunset",
	ABYSS = "abyss",
	CHRISTMAS = "christmas"
}

