name: 'main'
on:
  push:
    branches: [main]
    paths:
      - '*'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t kairos:latest .

      - name: Save Docker image as tar file
        run: docker save -o kairos.tar kairos:latest

      - name: Transfer Docker image and Docker Compose file to remote server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "kairos.tar,docker-compose.yaml"
          target: "/home/${{ secrets.USERNAME }}/kairos"
  
      - name: Deploy Docker containers using Docker Compose on remote server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: echo ${{ secrets.PASSWORD }} | sudo -S docker compose -f /home/${{ secrets.USERNAME }}/kairos/docker-compose.yaml up -d
            