name: 'main'
on:
  push:
    branches: [main]
    paths:
      - '*'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t kairos:latest .

      - name: Save Docker image as tar file
        run: docker save -o kairos.tar kairos:latest

      - name: Transfer Docker image and Docker Compose file to remote server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "kairos.tar,docker-compose.yaml"
          target: "/home/${{ secrets.USERNAME }}/kairos"
  
      - name: Deploy Docker containers using Docker Compose on remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} -p 7080 << 'ENDSSH'
            docker compose -f ${{ secrets.REMOTE_SERVER_PATH }}/docker-compose.yaml up -d
            ENDSSH